### ISSUE TITLE
Consider using `Math.round(step * 100) / 100`

### ISSUE THREAD

**Issue by yell0wd0g** [beaufortfrancois/sandbox#14]
Consider using `Math.round(step * 100) / 100` to throw away the (potentially many) decimals coming out of a `MediaSettingsRange.step` (re. https://crbug.com/723249 bug)

e.g. in line: 
https://github.com/beaufortfrancois/sandbox/blob/gh-pages/image-capture/playground.html#L199

**Comment by beaufortfrancois** [comment]
Fixed in https://github.com/beaufortfrancois/sandbox/commit/95a9d71211b8a53ec687240352145624b9a97919
Thank you!
