### ISSUE TITLE
"Get Started with Web Bluetooth" generator sometimes requires Web Bluetooth enabled

### ISSUE THREAD

**Issue by follower** [beaufortfrancois/sandbox#8]
The generator available at https://beaufortfrancois.github.io/sandbox/web-bluetooth/generator/ (via https://github.com/beaufortfrancois/sandbox/tree/gh-pages/web-bluetooth/generator) is a very useful tool. Thanks!

However using it when swapping between various browsers left me very confused as it would _mostly_ work in many cases except when specifying "Advertising Service UUID(s)".

What I've just realised is that because the code handling that part uses the `Bluetooth` object (for UUID manipulation) it only works if Web Bluetooth is enabled.

While it would be useful if the generator could be used without requiring Web Bluetooth (e.g. when creating a page in a laptop browser for deployment on a mobile browser), it would be helpful if the reason for the "invalid state" indicator (which on some platforms seems to briefly show the `Bluetooth` error as a tool tip?) was clearer--or simply a warning that that functionality wouldn't work.

(I link to the generator from my project notes page here: http://www.labradoc.com/i/follower/p/notes-web-bluetooth.)

Thanks!

**Comment by beaufortfrancois** [comment]
You are absolutely right! Let me update the generator code.

**Comment by beaufortfrancois** [comment]
And here it is https://github.com/beaufortfrancois/sandbox/commit/683942462ff9a17f2620bd60bca02e8e5a2a5bc4 @follower. You can now use the generator without Web Bluetooth flag at https://beaufortfrancois.github.io/sandbox/web-bluetooth/generator/.

Thank you Philip for this feedback.
I had a look at your project notes page and I loved the last Web Bluetooth reference ;)

![screenshot 2016-07-25 at 2 14 10 pm](https://cloud.githubusercontent.com/assets/634478/17100979/13f8c036-5272-11e6-8598-e29ba72f0958.png)

On a side note, where can I get a myelin heart pendant to test your demo at https://follower.github.io/web-bluetooth-demos/?

**Comment by follower** [comment]
Great, thanks for the fix. :) The generator is a really helpful tool to get started with Web Bluetooth.

The myelin heart pendant is a private project by a friend of mine. Flick an email to my username at rancidbacon.com and I can potentially put you in touch with him. Also, I'd like to tell you more about what I'm using Web Bluetooth for but would prefer to keep that to private email.

And, re: project notes page, ummm, whoops? :D

Thanks again!

**Comment by beaufortfrancois** [comment]
(email sent)
